version: 2
updates:
- package-ecosystem: pip
  directories: 
    - "/packages/abstractions"
    - "/packages/serialization/form"
    - "/packages/serialization/json"
    - "/packages/serialization/text"
    - "/packages/serialization/multipart"
    - "/packages/authentication/azure"
    - "/packages/http/httpx"
    - "/packages/tests/validation"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    open-telemetry:
      patterns:
        - "*opentelemetry*"
    pylint:
      patterns:
        - "*pylint*"
        - "*astroid*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10